### ISSUE TITLE
Error when running Example 1

### ISSUE THREAD

**Issue by YangLi-Bio** [krashkov/SteinerNet#2]
Hello!

I installed SteinerNet according to the documentation "https://www.rdocumentation.org/packages/SteinerNet/versions/2.0/topics/steinertree".
However, when I tried to run Example 1 in this link. I always got the error message "Error in V(g) : Not a graph object".

Could you please tell me how to solve this problem?

Thank you!

**Comment by krashkov** [comment]
Hi, @LiYangSDU!

**First**, note that your link points to an old version of SteinerNet, namely v2.0. A lot of changes have been made to SteinerNet as well as to the R core. Consequently, old documentation, to put it simply, is not applicable to the current version.

**Second**, in general you should use only official websites to find up-to-date documentation and supplementary materials. As for R packages they are:
1. corresponding GitHub repository;
2. [website](https://cran.r-project.org/web/packages/) maintained by R developers.

To put it in a nutshell, please, use up-to-date documentation which could be found [here](https://cran.r-project.org/web/packages/SteinerNet/index.html) or [here](https://github.com/krashkov/SteinerNet/tree/master/inst).

**Third**, @LiYangSDU, what result do you want to achieve? I mean, what version of R do you have now and what version of the package do you want to install (is v2.0 so important to you)?

**Comment by YangLi-Bio** [comment]
Hi Krashkov,

Thanks for your detailed explanation. According to your suggestions, I succeeded to run the functions in SteinerNet. My current problem is to solve the Steiner Tree Problem in a weighted graph, therefore, I am wondering whether this package is applicable for weighted graphs.

Thank you!

**Comment by krashkov** [comment]
@LiYangSDU, I asked this cause I though that you need the v2.0 specifically. Speaking about weighted graphs, this package does not provide this functionality. If you want to see specific functions, methods or algorithms, you can send me an email or, preferably, open a new issue with your suggestions or wishes.
